# Generated by Django 4.2.7 on 2025-10-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_adminmessage'),
    ]

    operations = [
    ]
