# Generated by Django 4.2.7 on 2025-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('account', 'Account Problem'), ('submission', 'Submission Issue'), ('contest', 'Contest Related'), ('feedback', 'Feedback/Suggestion')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='message_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('maintenance', 'Maintenance'), ('update', 'System Update'), ('contest', 'Contest News'), ('general', 'General News')], default='general', max_length=20),
        ),
    ]
