# Generated by Django 4.2.7 on 2025-10-11 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0005_adminmessage_category_adminmessage_is_resolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problemdiscussion',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemdiscussion',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminMessage',
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
        migrations.DeleteModel(
            name='DiscussionReply',
        ),
        migrations.DeleteModel(
            name='ProblemDiscussion',
        ),
    ]
