# Generated by Django 4.2.7 on 2025-10-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_announcement_announcementview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='announcementview',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcementview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='AnnouncementView',
        ),
    ]
