# Generated by Django 4.2.7 on 2025-10-11 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0008_alter_announcementview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
