# Generated by Django 5.2.6 on 2025-09-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-created_by__is_staff", "created_at"]},
        ),
    ]
