# Generated by Django 4.2.7 on 2025-10-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_note',
            field=models.CharField(blank=True, help_text='Optional explanation for sample input/output', max_length=500),
        ),
        migrations.AddField(
            model_name='testcase',
            name='note',
            field=models.CharField(blank=True, help_text='Optional note for this test case', max_length=200),
        ),
    ]
