# Generated by Django 4.2.7 on 2025-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest_only',
            field=models.BooleanField(default=False, help_text='Hide from public problem list, show only in contests'),
        ),
    ]
