# Generated by Django 4.2.7 on 2025-09-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_contest_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at']},
        ),
    ]
