# Generated by Django 4.2.7 on 2025-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'contest_only'], name='problems_pr_is_acti_2c7ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['category', 'difficulty'], name='problems_pr_categor_af19d5_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['created_at'], name='problems_pr_created_b0f0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['created_by'], name='problems_pr_created_0b18a7_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'is_sample'], name='problems_te_problem_de069b_idx'),
        ),
    ]
