# Generated by Django 4.2.7 on 2025-10-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'otp', 'is_verified'], name='accounts_ot_email_d83b3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_problems', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('preferred_language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python')], default='c', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['solved_problems'], name='accounts_us_solved__37774b_idx'), models.Index(fields=['total_submissions'], name='accounts_us_total_s_e09b32_idx')],
            },
        ),
    ]
