# Generated by Django 4.2.7 on 2025-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['email', 'otp', 'is_verified'], name='accounts_ot_email_d83b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['solved_problems'], name='accounts_us_solved__37774b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['total_submissions'], name='accounts_us_total_s_e09b32_idx'),
        ),
    ]
