# Generated by Django 4.2.7 on 2025-10-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python')], max_length=10)),
                ('code', models.TextField()),
                ('verdict', models.CharField(choices=[('QUEUED', 'Queued'), ('JUDGING', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('PE', 'Presentation Error')], default='QUEUED', max_length=10)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
                ('compilation_error', models.TextField(blank=True)),
                ('runtime_error', models.TextField(blank=True)),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('is_test', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='submissions_user_id_43efd8_idx'), models.Index(fields=['problem', '-submitted_at'], name='submissions_problem_d24719_idx'), models.Index(fields=['verdict'], name='submissions_verdict_223995_idx'), models.Index(fields=['user', 'problem', 'verdict'], name='submissions_user_id_177ec6_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx'), models.Index(fields=['user', 'verdict'], name='submissions_user_id_0016ee_idx')],
            },
        ),
    ]
