# Generated by Django 4.2.7 on 2025-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python')], max_length=10),
        ),
    ]
