# Generated by Django 4.2.7 on 2025-09-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='judged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('JUDGING', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('PE', 'Presentation Error')], default='QUEUED', max_length=10),
        ),
    ]
