# Generated by Django 4.2.7 on 2025-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_judged_at_alter_submission_verdict'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-submitted_at'], name='submissions_user_id_43efd8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-submitted_at'], name='submissions_problem_d24719_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['verdict'], name='submissions_verdict_223995_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', 'verdict'], name='submissions_user_id_177ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'verdict'], name='submissions_user_id_0016ee_idx'),
        ),
    ]
