# Generated by Django 4.2.7 on 2025-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_submissions_user_id_43efd8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python')], max_length=10),
        ),
    ]
