# Generated by Django 4.2.7 on 2025-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_remove_java_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
