# Generated by Django 4.2.7 on 2025-10-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True, help_text='Contest rules and guidelines')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='contests.ContestProblem', to='problems.problem'),
        ),
        migrations.AddIndex(
            model_name='contestproblem',
            index=models.Index(fields=['contest', 'order'], name='contests_co_contest_1be73f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['contest', '-total_score'], name='contests_co_contest_838c34_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['user'], name='contests_co_user_id_e52e7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together={('contest', 'user')},
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_active', '-start_time'], name='contests_co_is_acti_c45e73_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time', 'end_time'], name='contests_co_start_t_72f0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['slug'], name='contests_co_slug_fe75b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['created_by'], name='contests_co_created_1b90ff_idx'),
        ),
    ]
