# Generated by Django 4.2.7 on 2025-09-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_rules'),
    ]

    operations = [
    ]
