# Generated by Django 4.2.7 on 2025-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20250930_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rules',
            field=models.TextField(blank=True, help_text='Contest rules and guidelines'),
        ),
    ]
