# Generated by Django 4.2.7 on 2025-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20250930_1423'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_active', '-start_time'], name='contests_co_is_acti_c45e73_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time', 'end_time'], name='contests_co_start_t_72f0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['slug'], name='contests_co_slug_fe75b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['created_by'], name='contests_co_created_1b90ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['contest', '-total_score'], name='contests_co_contest_838c34_idx'),
        ),
        migrations.AddIndex(
            model_name='contestparticipation',
            index=models.Index(fields=['user'], name='contests_co_user_id_e52e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='contestproblem',
            index=models.Index(fields=['contest', 'order'], name='contests_co_contest_1be73f_idx'),
        ),
    ]
