# Generated by Django 4.2.7 on 2025-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_contests_co_is_acti_c45e73_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
